version: '3.1'
services:
  mariadb:
    image: mariadb
    volumes:
      - ../${MARIADB_DATA_DIR}:/var/lib/mysql
    healthcheck:
      test: bash -c "mysqladmin ping -s"
      interval: 1s
      timeout: 1s
      retries: 120
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306

  backend-remote:
    image: docker.breakout.xyz:5000/breakout-backend:${BACKEND_VERSION}
    healthcheck:
      test: bash -c "curl localhost:8082/"
      interval: 1s
      timeout: 1s
      retries: 120
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    links:
      - mariadb
    ports:
      - 8082:8082
    command: java -Dspring.cache.type=simple -Dspring.datasource.url=jdbc:mysql://mariadb:3306/${MYSQL_DATABASE} -server -jar /usr/src/myapp/app.jar

  backend-local:
    image: java:openjdk-8-jdk
    volumes:
      - ../${BACKEND_TMP_DIR}/app.jar:/usr/src/app.jar
    healthcheck:
      test: bash -c "curl localhost:8082/"
      interval: 1s
      timeout: 1s
      retries: 120
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    links:
      - mariadb
    ports:
      - 8082:8082
    command: java -Dspring.cache.type=simple -Dspring.datasource.url=jdbc:mysql://mariadb:3306/${MYSQL_DATABASE} -server -jar /usr/src/app.jar